version: '3.8'

services:
  api:
    build: .
    ports:
      - \"8000:8000\"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - PYTHONPATH=/app
    volumes:
      - ./assistant_demo.db:/app/assistant_demo.db
      - ./data:/app/data
    healthcheck:
      test: [\"CMD\", \"curl\", \"-f\", \"http://localhost:8000/api/health\"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  streamlit:
    build: .
    ports:
      - \"8501:8501\"
    environment:
      - API_BASE=http://api:8000
    command: [\"streamlit\", \"run\", \"streamlit/demo_streamlit.py\", \"--server.address\", \"0.0.0.0\", \"--server.port\", \"8501\"]
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    name: assistant-demo-network